//This file was generated by script mkregs.py



//write registers
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 0), TIMER_RESET, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 1), TIMER_ENABLE, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 2), TIMER_SAMPLE, wdata[1-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 3), TIMER_WRAP_HIGH, wdata[`WDATA_W-1:0])
`REG_ARE(clk, rst, 0, valid & wstrb & (address == 4), TIMER_WRAP_LOW, wdata[`WDATA_W-1:0])


//read registers
`SIGNAL(rdata_int, DATA_W)
`SIGNAL2OUT(rdata, rdata_int)

always @* begin
   rdata_int = 1'b0;
   case(address)
     5: rdata_int = TIMER_DATA_HIGH;
     6: rdata_int = TIMER_DATA_LOW;
     default: rdata_int = 1'b0;
   endcase
end
`SIGNAL(ready_int, 1)
`REG_AR(clk, rst, 0, ready_int, valid)
`SIGNAL2OUT(ready, ready_int)
