//This file was generated by script mkregs.py

//register address mapping
#define TIMER_RESET 0
#define TIMER_ENABLE 1
#define TIMER_SAMPLE 2
#define TIMER_WRAP_HIGH 3
#define TIMER_WRAP_LOW 4
#define TIMER_DATA_HIGH 5
#define TIMER_DATA_LOW 6
